vich_uploader:
  db_driver: orm
  mappings:
    articles:
      uri_prefix: "/uploads/articles"
      upload_destination: "%kernel.project_dir%/public/uploads/articles"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: true
